### ISSUE TITLE
vue-icomoon problem using size prop as string

### ISSUE THREAD

**Issue by dan-bowen** [dan-bowen/nuxt-blog-starter#3]
Receiving this cli warning

```
[Vue warn]: Invalid prop: type check failed for prop "size". Expected Number with value NaN, got String with value "20px".
```

More details in the issue filed below.

https://github.com/aykutkardas/vue-icomoon/issues/9

**Comment by aykutkardas** [comment]
Thank you for report thist issue. Fixed. Try `version: 0.3.2`

**Comment by dan-bowen** [comment]
This works great. Thanks @aykutkardas
