### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by dan-bowen** [dan-bowen/nuxt-blog-starter#6]
In chrome devtools

```
fetch.mjs?v=dd314639:131          GET http://localhost:3000/api/_content/query?_params={%22where%22:[{%22_path%22:%22/%22}],%22first%22:true,%22sort%22:[{%22_file%22:1,%22$numeric%22:true}]}&previewToken 404 (Document not found!)
```

https://github.com/nuxt/content/issues/1513

**Comment by farnabaz** [comment]
I believe this is not the same issue, all you need is to disable `documentDriven` on the index page https://content.nuxtjs.org/guide/writing/document-driven#disable-document-driven

**Comment by dan-bowen** [comment]
Thank you for the pointer @farnabaz. I never would have found that.

Much appreciated 🙏
